import Head from 'next/head'
import Footer from '../components/Footer'
import Hero from '../components/Hero'
import Instagram from '../components/Instagram'
import Slider from '../components/Slider'
import { SliderData } from '../components/SliderData'

export default function Home() {
  return (
    <div>
      <Head>
        <title>Sameer Photography</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />        
      </Head>
      <Hero heading='Sameer Photography' message="I don’t trust words. I trust pictures.."/>
      <Slider slides={SliderData}/>
      <Instagram/>
      <Footer/>
    </div>
  )
}
